name: Automate Data Integration

on:
  push:
    paths:
      - "**/*"

jobs:
  integrate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Debug File Structure
        run: ls -R

      - name: Make script executable
        run: chmod +x integrate_data.sh

      - name: Run integration script
        run: ./integrate_data.sh     